package gui;

import javafx.application.Application;

/**
 * This provides an entry point to the application and will
 * launch the GUI application.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @author Josh Archer
 * @version 1.0
 */
public class GUILauncher
{
    /**
     * Primary entry point to the application.
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args)
    {
        Application.launch(DictionarySearchGUI.class);
    }
}
